<?php

/**
 * @file
 * Implementation de notre hook.
 */

use Drupal\Core\Access\AccessResult;


/**
 * Implements hook_theme().
 */
function demo_baggage_theme ($existing, $type, $theme, $path) {
  return [
    'recettes-liste' => [
      'variables' => [
        'items' => [],
        'title' => '',
      ]
    ],
    'salah' => [
      'variables' => [
        'items' => [],
        'title' => '',
        'nom' => '',
      ]
    ],
    'bienvenue' => [
      'variables' => [
        'items' => [],
        'title' => '',
        'nom' => '',
      ]
    ]
  ];
}






